---
schema: 1
job: extension
config:
  name: ${JOB_NAME}
  process:
  - type: diffusion_trainer
    training_folder: ${OUTPUT_DIR}
    network:
      type: lora
      linear: 32
      linear_alpha: 32
      conv: 16
      conv_alpha: 16
    datasets:
    - folder_path: ${DATASET_DIR}
      caption_ext: txt
      caption_dropout_rate: 0.05
      shuffle_tokens: false
      cache_latents_to_disk: true
      resolution:
      - 512
      - 768
      - 1024
      num_frames: 1
      fps: 1
    train:
      batch_size: 1
      gradient_accumulation: 1
      train_unet: true
      train_text_encoder: false
      gradient_checkpointing: true
      optimizer: adamw8bit
      lr: 0.0001
      lr_scheduler: constant
      noise_scheduler: ddpm
      dtype: bf16
      loss_type: mse
      steps: 3000
      content_or_style: content
      timestep_type: sigmoid
      cache_text_embeddings: false
    model:
      name_or_path: stabilityai/stable-diffusion-xl-base-1.0
      arch: sdxl
      quantize: false
      quantize_te: false
    save:
      dtype: bf16
      save_format: diffusers
      save_every: 250
      max_step_saves_to_keep: 4
      push_to_hub: false
    logging:
      use_ui_logger: true
      use_wandb: false
    sample:
      sampler: ddpm
      sample_every: 250
      sample_start_step: 0
      seed: 42
      walk_seed: false
      width: 1024
      height: 1024
      guidance_scale: 6
      sample_steps: 30
      num_frames: 1
      fps: 1
      samples:
      - prompt: A detailed portrait of [trigger] in natural light
